version: '3.5'
services:
  db:
    image: mysql
    container_name: algamoney_mysql
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - algamoney_data:/var/lib/mysql

volumes:
  algamoney_data:

