version: '3.8'
services:
  db:
    image: mariadb
    container_name: algamoney_mariadb
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - algamoney_data:/var/lib/mysql

volumes:
  algamoney_data:

